import React from 'react'
import { Carousel, Container } from '../components/index.js'

function Home() {
  return (
    <Container>
        <Carousel />
        <div className='h-[200vh]'>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut nam impedit libero molestias id, eaque ab praesentium est assumenda cum maxime explicabo hic quia non sint! Cum beatae eius commodi? Nam quos recusandae odit ipsam illum possimus quae reiciendis corporis. Nemo corporis consequuntur et minus eveniet excepturi vero fuga nulla sed deleniti ipsum sint cupiditate, voluptatem illo veritatis placeat reiciendis earum. Esse corrupti est, iure exercitationem consectetur magni reiciendis eaque explicabo cumque voluptate incidunt temporibus id nihil delectus sint ratione pariatur doloribus quia veniam ad autem repudiandae, voluptates commodi. Deleniti, nam non. Maxime ea officiis, quis quas aut vero consequatur?
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil sint velit necessitatibus unde natus? Fugit ratione eos dolores voluptatibus ex aliquam esse ad saepe reprehenderit, soluta, amet cum consequatur sequi corporis quas ea inventore laborum, eaque iusto asperiores culpa rem? Odit iusto id eaque. Debitis iste ipsam ratione, quam maiores quas quis, ab qui sint fugiat delectus tenetur amet fugit. Nulla iste nesciunt ea molestias esse, animi perferendis placeat cumque magni repellendus excepturi itaque temporibus, sint molestiae natus iusto quae! Velit delectus, consequuntur molestiae quis laboriosam sit labore praesentium tempora officia recusandae facere ut beatae commodi incidunt. Eos vel nisi, nesciunt debitis molestiae et inventore excepturi impedit? Praesentium ipsam fugiat ipsum tempora rerum unde nobis sapiente, dolorum tenetur? Adipisci nihil commodi rerum debitis consectetur exercitationem autem rem illum repellendus odio quibusdam nam sed fugit quas ratione harum, at eveniet consequatur reiciendis hic eum ab animi. Consectetur fugiat exercitationem nesciunt qui! Voluptates est in eligendi voluptatibus aperiam ipsum nemo optio perspiciatis ex autem, a non voluptatem, aut ut et reiciendis! Assumenda sit laudantium eveniet alias placeat ut nemo, deserunt, eum unde architecto odio dicta? Voluptatibus nemo labore non molestias officia blanditiis temporibus quia porro molestiae. Ab nesciunt exercitationem at laboriosam unde eligendi nobis, officiis, velit, rerum commodi corporis debitis. Iusto amet expedita non tempora explicabo! Quasi neque dolorem veritatis provident magnam ab obcaecati, magni nesciunt illum exercitationem nobis totam aperiam alias ea minima labore placeat quaerat ducimus eos iure enim sunt molestias et natus? Maxime tenetur praesentium error, odio excepturi labore hic deserunt ipsa pariatur, harum neque qui, ipsum quidem dolore ullam voluptate rerum facere voluptas? Fugiat modi nisi velit consectetur maiores architecto hic! Quibusdam delectus, quasi repellat soluta voluptate nam maiores nulla iusto facere sed quos magnam aut sint asperiores, veniam nisi recusandae aliquid inventore reiciendis. Odio nobis sed, numquam enim minus libero. Suscipit dolores minima, odio quam modi vitae, odit quas perferendis repellat eveniet impedit eum, animi voluptatum magni laboriosam soluta tenetur totam quaerat ipsum dolore incidunt! Beatae libero nihil totam perspiciatis nemo, nisi iste dicta eum, veniam, provident enim natus aperiam optio possimus blanditiis distinctio asperiores animi facere laborum deserunt qui tenetur culpa. Iste aspernatur recusandae, doloremque necessitatibus laudantium corrupti aliquid rem ea obcaecati reprehenderit hic quo maxime est possimus dolorem omnis cumque facilis aliquam. Eaque, quibusdam. Unde numquam consectetur incidunt cupiditate laudantium dolore id earum dolorem beatae vero, maiores, voluptas illo! Numquam, atque sint! Architecto, quidem itaque.
        </div>
    </Container>
  )
}

export default Home